### ISSUE TITLE
sidebar covers banner when width is too small

### ISSUE THREAD

**Issue by DolphinDTM** [zardoru/becgi#5]
needs some more responsive design. solutions
- make the sidebar appear on the bottom.
- make the banner automatically resize based on screen/window width.
- move the sidebar lower than the banner.

**Comment by zardoru** [comment]
banner's size is fixed, so I'm not sure how to address this...

**Comment by DolphinDTM** [comment]
idk make it so that the sidebar has a div class that makes it moves whenever the window width is too small as seen here http://www.w3schools.com/html/html_responsive.asp personally i don't understand it cause im terribad at this stuff
this means the actually contents of the page and the sidebar both need div classes.
