### ISSUE TITLE
Pre-reserve logo area

### ISSUE THREAD

**Issue by suitougreentea** [zardoru/becgi#7]
Is it possible to pre-reserve logo image area when users load a page?

Each time the user access a page, first the top of the page doesn't show a logo, then the page is expanded vertically by image size, and then loads image.
This behavior might be a bit nuisance because the menu momentarily goes up so user's cursor would wander. (sorry for lack of expression)

I'm not familiar with html/css, so I don't know if it is possible.
If possible, please fix.

**Comment by zardoru** [comment]
I wonder if it can be done by merely setting width and height to the image.
In that case, I believe that could be good enough.

**Comment by DolphinDTM** [comment]
@zardoru We could make the header a fixed size in the external css. This shouldn't break the responsiveness.

**Comment by DolphinDTM** [comment]
fixed as of https://github.com/zardoru/becgi/pull/10
