### ISSUE TITLE
bmwest.tk refuses jumps to some external pages

### ISSUE THREAD

**Issue by suitougreentea** [zardoru/becgi#8]
I use Google Chrome and get following error message when I attempt to jump to some external pages.

I can jump to some pages such as https://bemuse.ninja/ but browser's address bar won't change.

Both issues may be came from the frame embedded in http://bmwest.tk/ . Of course it works fine when I access http://bmwest.herokuapp.com/ .

It is better to register custom domain for Heroku app if possible.

```
Refused to display 'https://twitter.com/wosderge' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
Refused to display 'https://github.com/CircularRhythm/CircularRhythm/wiki/(Temporary)-How-to-create-notecharts-for-CircularRhythm' in a frame because it set 'X-Frame-Options' to 'deny'.
```

**Comment by DolphinDTM** [comment]
The issue is that we're awfully low-budget and the .tk domain only cloaks the bmwest.herokuapp.com URL.
Setting up a domain name will cost money which makes things difficult since neither me nor Agka have credit cards

**Comment by suitougreentea** [comment]
Ah, I just came to know .tk can be registered for free. Is bmwest.tk also free domain?

If so, you cannot apply this measure with this .tk domain? https://devcenter.heroku.com/articles/custom-domains

**Comment by DolphinDTM** [comment]
This seems to be impossible, as using custom domains require the owner of the Heroku App to be verified. To be verified you need to add a credit card to your account. I can make the bmwest.tk domain redirect instead of cloaking, to get around this issue.

**Comment by suitougreentea** [comment]
I understood. Redirecting is a good solution. Thank you!

**Comment by suitougreentea** [comment]
Seems working correctly!

**Comment by suitougreentea** [comment]
This reference is my mistake, sorry.

**Comment by DolphinDTM** [comment]
No worries.
